config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
 
  resources :coins

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { minimum: 3 }

  validates :value, presence: true, numericality: { only_integer: true, greater_than: 0 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  def index
    @coins = Coin.all
  end
  
  def show
    @coin = Coin.find(params[:id])
  end
 
  def new
    @coin = Coin.new
  end

  def edit
    @coin = Coin.find(params[:id])
  end

  def create
    @coin = Coin.new(coin_params)
  
    if @coin.save
      redirect_to @coin

    else 
      render 'new'
    end
  end

  def update
    @coin = Coin.find(params[:id])
   
    if @coin.update(coin_params)
      redirect_to @coin
    else
      render 'edit'
    end
  end

  def destroy
    @coin = Coin.find(params[:id])
    @coin.destroy
   
    redirect_to coins_path
  end

  private
  def coin_params
    params.require(:coin).permit(:name, :value)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/coins/_form.html.erb
<%= form_with model: @coin, local: true do |form| %>
  
  <% if @coin.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@coin.errors.count, "error") %> prohibited
        this coin from being saved:
      </h2>
      <ul>
        <% @coin.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :value %><br>
    <%= form.number_field :value %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/coins/edit.html.erb
<h1>Edit coin</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', coins_path %>

app/views/coins/index.html.erb
<h1>All coins</h1>
 
<table>
  <tr>
    <th>Coin</th>
    <th>Value</th>
    <th colspan="2"></th>
  </tr>
 
  <% @coins.each do |coin| %>
    <tr>
      <td><%= coin.name %></td>
      <td><%= coin.value %></td>
      <td><%= link_to 'Show', coin_path(coin) %></td>
      <td><%= link_to 'Edit', edit_coin_path(coin) %></td>
      <td><%= link_to 'Destroy', coin_path(coin),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

<%= link_to 'New Coin', new_coin_path %>

app/views/coins/new.html.erb
<h1>New Coin</h1>

<%= render 'form' %>

<%= link_to 'Back', coins_path %>

app/views/coins/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @coin.name %>
</p>
 
<p>
  <strong>Value:</strong>
  <%= @coin.value %>
</p>

<%= link_to 'Edit', edit_coin_path(@coin) %> |
<%= link_to 'All Coins', coins_path %>

app/views/home/index.html.erb
<h1>Coin Machine</h1>
<%= link_to 'Coin Bank', controller: 'coins' %>
<%= link_to 'New Coin', new_coin_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoinMachine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>